//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyShoppingWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public class OrderStatuses
    {
    
        public int Id { get; set; }
        public string StatusName { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
