//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyShoppingWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public class Orders
    {
        public int Id { get; set; }
        public string CustomerName { get; set; }
        public string CustomerEmail { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerPhone { get; set; }

        public Nullable<int> UserId { get; set; }

        [ForeignKey("UserId")]
        public virtual TblUsers TblUsers { get; set; }
        public int StatusId { get; set; }

        [ForeignKey("StatusId")]
        public virtual OrderStatuses OrderStatuses { get; set; }
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
    }
}
