//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyShoppingWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public class Products
    {
        public int Id { get; set; }

        [Required]
        public string ProductName { get; set; }
        public double UnitPrice { get; set; }
        public Nullable<double> DiscountRatio { get; set; }
        public Nullable<System.DateTime> DiscountExpiry { get; set; }
        public bool? IsActive { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string ImgUrl { get; set; }
        public string Description { get; set; }

        [ForeignKey("CategoryId")]
        public virtual Categories Categories { get; set; }
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }

        public Products()
        {
            IsActive = true;
        }
    }
}
