//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyShoppingWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public class TblUsers
    {
    
        public int Id { get; set; }

        [StringLength(50)]
        [Index(IsUnique = true)]
        [Required]
        public string Email { get; set; }

        [Required]
        public string Password { get; set; }

        [Required]
        public string FullName { get; set; }
        public string Address { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual ICollection<UserRoles> UserRoles { get; set; }
    }
}
